//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoSpeed_Orlov.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationDbContext : DbContext
    {

        private static ApplicationDbContext _instance;

        public ApplicationDbContext()
            : base("name=ApplicationDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static ApplicationDbContext GetContext()
        {
            if (_instance == null)
            {
                _instance = new ApplicationDbContext();
            }
            return _instance;
        }

        public virtual DbSet<Building_Materials> Building_Materials { get; set; }
        public virtual DbSet<Storage> Storages { get; set; }
    }
}
